testing foritfy

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -26,30 +26,50 @@ jobs:
         run: npm ci
       
       - name: Run tests
-        run: npm test || echo "No tests found!"
+        run: npm test || echo "No tests found, would add tests in a real project"
 
-  sonar:
-    name: Static Code Analysis - SonarQube
-    runs-on: windows-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  fortify:
+    name: Static Code Analysis - Fortify
+    runs-on: ubuntu-latest
+    steps:    
+      - name: Check out source code
+        uses: actions/checkout@v4  
+      - name: Run Fortify on Demand SAST & SCA Scan
+        uses: fortify/github-action@v1
         with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
-      - name: Scan for Vulnerabilities (SAST and SCA)
-        uses: SonarSource/sonarqube-scan-action@v4
+          sast-scan: true
+          debricked-sca-scan: true
         env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
-      - uses: SonarSource/sonarqube-quality-gate-action@v1
-        timeout-minutes: 5
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} #testing
-          
+          FOD_URL: https://trial.fortify.com
+          FOD_CLIENT_ID: a2050b40-a391-404d-bbd8-e1913b85ca46
+          FOD_CLIENT_SECRET: MClmVnRnUGg1WU11bUkoM3BzQnN1bmc5JHg5YVdy0
+          FOD_RELEASE: javaBenchmark:benchmark
+          DO_SETUP: true
+          # SETUP_ACTION: https://scm.my.org/shared-repos/fcli-actions/setup.yaml
+          SETUP_ACTION: --copy-from "${{ github.repository }}:${{ github.event.repository.default_branch }}"
+          # SC_CLIENT_VERSION: 24.4.1
+          # DO_PACKAGE_DEBUG: true
+          # PACKAGE_EXTRA_OPTS: src/components
+          # FOD_SAST_SCAN_EXTRA_OPTS:
+          # DO_WAIT: true
+          # DO_POLICY_CHECK: true
+          # POLICY_CHECK_ACTION: https://scm.my.org/shared-repos/fcli-actions/check-policy.yaml
+          # POLICY_CHECK_EXTRA_OPTS: --on-unsigned=ignore
+          # DO_JOB_SUMMARY: true
+          # JOB_SUMMARY_ACTION: https://scm.my.org/shared-repos/fcli-actions/job-summary.yaml
+          # JOB_SUMMARY_EXTRA_OPTS: --on-unsigned=ignore
+          # DO_PR_COMMENT: true
+          # PR_COMMENT_ACTION: https://scm.my.org/shared-repos/fcli-actions/github-pr-comment.yaml
+          # PR_COMMENT_EXTRA_OPTS: --on-unsigned=ignore
+          # DO_EXPORT: true
+          # EXPORT_ACTION: https://scm.my.org/shared-repos/fcli-actions/github-sast-report.yaml
+          # EXPORT_EXTRA_OPTS: --on-unsigned=ignore
+          # TOOL_DEFINITIONS: https://ftfy.mycompany.com/tool-definitions/v1/tool-definitions.yaml.zip
+
   build:
     name: Build
     runs-on: ubuntu-latest
-    needs: [test, sonar]
+    needs: [test, fortify]
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -149,120 +169,120 @@ jobs:
         id: set_output
         run: echo "image_tag=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
 
-      - name: Run container for BurpSuite testing
-        run: |
-          NEW_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:sha-${{ github.sha }}
-
-          # Configuration variables
-          SSH_KEY_PATH="$HOME/.ssh/id_rsa_autossh"
-          CONTAINER_NAME="autoburp"
-          REMOTE_PORT=80
-          LOCAL_SERVER="172.17.0.1"
-          LOCAL_PORT=1010
-          SSH_SERVER="serveo.net"
-          OUTPUT_FILE="output.txt"
-
-          docker run -d -p $LOCAL_PORT:$REMOTE_PORT  "$NEW_IMAGE"
-          sleep 10  # Give the app time to start
-          curl -v http://localhost:"$LOCAL_PORT" || exit 1
-
-          # Clear previous output and keys
-          echo "Cleaning up previous files..."
-          : > output.txt
-          rm -f "$SSH_KEY_PATH"*
-          docker remove -f $CONTAINER_NAME
-
-          # Generate SSH key
-          echo "Generating new SSH key..."
-          ssh-keygen -q -t ed25519 -a 100 -f "$SSH_KEY_PATH" -N "" -C "autossh-key"
-
-          # Pull autossh
-          echo "Pulling autossh...."
-          docker pull aranajuan/autossh
-
-          echo $SSH_KEY_PATH
-
-          # Run the container with AutoSSH
-          echo "Starting AutoSSH tunnel..."
-          docker run -d -it --rm --name "$CONTAINER_NAME" \
-              -v ${SSH_KEY_PATH}:${SSH_KEY_PATH} \
-              aranajuan/autossh \
-              autossh -M 0 -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -o "ServerAliveInterval 30" -o "ServerAliveCountMax 3" \
-              -R $REMOTE_PORT:"$LOCAL_SERVER":$LOCAL_PORT "$SSH_SERVER"
-
-          sleep 5
-
-          #Pipeline the result of autossh to OUTPUT_FILE
-          docker logs "$CONTAINER_NAME" > "$OUTPUT_FILE"
-
-          echo "AutoSSH container is running..."
-
-          echo "Waiting for Serveo URL..."
-          timeout=60
-          while ! grep -q "Forwarding HTTP traffic" "$OUTPUT_FILE" && [ $timeout -gt 0 ]; do
-            sleep 1
-            ((timeout--))
-          done
-
-          if [ $timeout -eq 0 ]; then
-            echo "Timed out waiting for Serveo URL"
-            echo "logs:" >> "$OUTPUT_FILE"
-            docker logs "$CONTAINER_NAME" >> "$OUTPUT_FILE"
-            exit 1
-          fi
-
-          # Extract URL from the output
-          public_url=$(grep "Forwarding HTTP traffic" "$OUTPUT_FILE" | sed -n 's/.*Forwarding HTTP traffic from //p' | tr -d '\r\n')
-          
-          echo "Your public App URL is: $public_url"
-
-
-          # Build the JSON payload with jq
-          json_payload=$(jq -n --arg url "$public_url" '{
-          scan_configurations: [{
-            name: "Crawl strategy - fastest",
-            type: "NamedConfiguration"
-          }],
-          urls: [$url]
-          }')
-
-          # Send the POST request and capture the Location header
-          scan_id=$(curl -s -D - -o /dev/null -X POST \
-            -H "Content-Type: application/json" \
-            -d "$json_payload" \
-            "https://df547105d95c5c5f411f593ac9f518a5.serveo.net/v0.1/scan" \
-            | awk '/^location:/ { print $2 }' | tr -d '\r')
-
-          echo "Scan ID: $scan_id"
-
-          scan_result="https://df547105d95c5c5f411f593ac9f518a5.serveo.net/v0.1/scan/$scan_id"
-
-          echo "Waiting for scan to complete..."
-          retries=60  
-          while [ $retries -gt 0 ]; do
-          result=$(curl -s -X GET "$scan_result")
-          progress=$(echo "$result" | jq '.scan_metrics.crawl_and_audit_progress // 0')
-  
-          echo "Progress: $progress%"
-          if [ "$progress" -eq 100 ]; then
-          echo "Scan complete."
-          echo "$result"
-          # Check for high severity issues
-          echo "$result" | jq '
-            [.issue_events[]?.issue.severity] | any(. == "medium")
-          ' | grep -q true && exit 1
-
-          exit 0
-          fi
-
-          sleep 5
-          ((retries--))
-          done
-
-          echo "Timed out waiting for scan to complete."
-          exit 1
-
-
+      #- name: Run container for BurpSuite testing
+      #  run: |
+      #    NEW_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:sha-${{ github.sha }}
+#
+      #    # Configuration variables
+      #    SSH_KEY_PATH="$HOME/.ssh/id_rsa_autossh"
+      #    CONTAINER_NAME="autoburp"
+      #    REMOTE_PORT=80
+      #    LOCAL_SERVER="172.17.0.1"
+      #    LOCAL_PORT=1010
+      #    SSH_SERVER="serveo.net"
+      #    OUTPUT_FILE="output.txt"
+#
+      #    docker run -d -p $LOCAL_PORT:$REMOTE_PORT  "$NEW_IMAGE"
+      #    sleep 10  # Give the app time to start
+      #    curl -v http://localhost:"$LOCAL_PORT" || exit 1
+#
+      #    # Clear previous output and keys
+      #    echo "Cleaning up previous files..."
+      #    : > output.txt
+      #    rm -f "$SSH_KEY_PATH"*
+      #    docker remove -f $CONTAINER_NAME
+#
+      #    # Generate SSH key
+      #    echo "Generating new SSH key..."
+      #    ssh-keygen -q -t ed25519 -a 100 -f "$SSH_KEY_PATH" -N "" -C "autossh-key"
+#
+      #    # Pull autossh
+      #    echo "Pulling autossh...."
+      #    docker pull aranajuan/autossh
+#
+      #    echo $SSH_KEY_PATH
+#
+      #    # Run the container with AutoSSH
+      #    echo "Starting AutoSSH tunnel..."
+      #    docker run -d -it --rm --name "$CONTAINER_NAME" \
+      #        -v ${SSH_KEY_PATH}:${SSH_KEY_PATH} \
+      #        aranajuan/autossh \
+      #        autossh -M 0 -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -o "ServerAliveInterval 30" -o "ServerAliveCountMax 3" \
+      #        -R $REMOTE_PORT:"$LOCAL_SERVER":$LOCAL_PORT "$SSH_SERVER"
+#
+      #    sleep 5
+#
+      #    #Pipeline the result of autossh to OUTPUT_FILE
+      #    docker logs "$CONTAINER_NAME" > "$OUTPUT_FILE"
+#
+      #    echo "AutoSSH container is running..."
+#
+      #    echo "Waiting for Serveo URL..."
+      #    timeout=60
+      #    while ! grep -q "Forwarding HTTP traffic" "$OUTPUT_FILE" && [ $timeout -gt 0 ]; do
+      #      sleep 1
+      #      ((timeout--))
+      #    done
+#
+      #    if [ $timeout -eq 0 ]; then
+      #      echo "Timed out waiting for Serveo URL"
+      #      echo "logs:" >> "$OUTPUT_FILE"
+      #      docker logs "$CONTAINER_NAME" >> "$OUTPUT_FILE"
+      #      exit 1
+      #    fi
+#
+      #    # Extract URL from the output
+      #    public_url=$(grep "Forwarding HTTP traffic" "$OUTPUT_FILE" | sed -n 's/.*Forwarding HTTP traffic from //p' | tr -d '\r\n')
+      #    
+      #    echo "Your public SonarQube URL is: $public_url"
+#
+#
+      #    # Build the JSON payload with jq
+      #    json_payload=$(jq -n --arg url "$public_url" '{
+      #    scan_configurations: [{
+      #      name: "Crawl strategy - fastest",
+      #      type: "NamedConfiguration"
+      #    }],
+      #    urls: [$url]
+      #    }')
+#
+      #    # Send the POST request and capture the Location header
+      #    scan_id=$(curl -s -D - -o /dev/null -X POST \
+      #      -H "Content-Type: application/json" \
+      #      -d "$json_payload" \
+      #      "https://7db9d55a057cc510340c4ed052181246.serveo.net/v0.1/scan" \
+      #      | awk '/^location:/ { print $2 }' | tr -d '\r')
+#
+      #    echo "Scan ID: $scan_id"
+#
+      #    scan_result="https://7db9d55a057cc510340c4ed052181246.serveo.net/v0.1/scan/$scan_id"
+#
+      #    echo "Waiting for scan to complete..."
+      #    retries=60  
+      #    while [ $retries -gt 0 ]; do
+      #    result=$(curl -s -X GET "$scan_result")
+      #    progress=$(echo "$result" | jq '.scan_metrics.crawl_and_audit_progress // 0')
+  #
+      #    echo "Progress: $progress%"
+      #    if [ "$progress" -eq 100 ]; then
+      #    echo "Scan complete."
+      #    echo "$result"
+      #    # Check for high severity issues
+      #    echo "$result" | jq '
+      #      [.issue_events[]?.issue.severity] | any(. == "medium")
+      #    ' | grep -q true && exit 1
+#
+      #    exit 0
+      #    fi
+#
+      #    sleep 5
+      #    ((retries--))
+      #    done
+#
+      #    echo "Timed out waiting for scan to complete."
+      #    exit 1
+#
+#
   update-k8s:
     name: Update Kubernetes Deployment
     runs-on: ubuntu-latest
